// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY-FNipPfTe84ALuGSpoUejTKv0vOxtTU',
    appId: '1:845077720591:web:491fe4ccd772d6601f7d7a',
    messagingSenderId: '845077720591',
    projectId: 'vidalossa-9500b',
    authDomain: 'vidalossa-9500b.firebaseapp.com',
    storageBucket: 'vidalossa-9500b.appspot.com',
    measurementId: 'G-G2HM0PRNJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBRbQpIFzgjA5wkZe4hfbAFHq9TPhsOBs',
    appId: '1:845077720591:android:cdb0275f6618bc371f7d7a',
    messagingSenderId: '845077720591',
    projectId: 'vidalossa-9500b',
    storageBucket: 'vidalossa-9500b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT3RJwIiCQrhEKHSnV-IYtiB65Np9Y9-8',
    appId: '1:845077720591:ios:33434a27a91fa25a1f7d7a',
    messagingSenderId: '845077720591',
    projectId: 'vidalossa-9500b',
    storageBucket: 'vidalossa-9500b.appspot.com',
    iosClientId: '845077720591-80eet8526h03evb85t46hpf33pj8j53i.apps.googleusercontent.com',
    iosBundleId: 'com.example.vidalossa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT3RJwIiCQrhEKHSnV-IYtiB65Np9Y9-8',
    appId: '1:845077720591:ios:33434a27a91fa25a1f7d7a',
    messagingSenderId: '845077720591',
    projectId: 'vidalossa-9500b',
    storageBucket: 'vidalossa-9500b.appspot.com',
    iosClientId: '845077720591-80eet8526h03evb85t46hpf33pj8j53i.apps.googleusercontent.com',
    iosBundleId: 'com.example.vidalossa',
  );
}
